# Generated by Django 4.1.7 on 2023-03-16 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('telefono', models.CharField(max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('grupos', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece el usuario.', related_name='usuarios_grupos', to='auth.group', verbose_name='grupos')),
                ('permisos', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuarios_permisos', to='auth.permission', verbose_name='permisos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.IntegerField()),
                ('especialidades', models.ManyToManyField(to='Gestion.especialidadmedica')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('direccion', models.CharField(max_length=70)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_obra_social', models.CharField(blank=True, max_length=50, null=True)),
                ('obras_sociales', models.ManyToManyField(blank=True, to='Gestion.obrasocial')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('confirmado', models.BooleanField(default=False)),
                ('obra_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.obrasocial')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='Gestion.turno')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vigencia', models.DateTimeField()),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.obrasocial')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.medico')),
            ],
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='medicos',
            field=models.ManyToManyField(blank=True, through='Gestion.PrecioConsulta', to='Gestion.medico'),
        ),
        migrations.AddField(
            model_name='medico',
            name='obra_social',
            field=models.ManyToManyField(blank=True, through='Gestion.PrecioConsulta', to='Gestion.obrasocial'),
        ),
        migrations.AddField(
            model_name='especialidadmedica',
            name='medicos',
            field=models.ManyToManyField(to='Gestion.medico'),
        ),
    ]
