# Generated by Django 4.1.7 on 2023-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_alter_turno_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='pacientes',
            field=models.ManyToManyField(blank=True, to='Gestion.paciente'),
        ),
    ]
